name: "RTSP Recorder"
version: "1.0.5"
slug: "rtsp_recorder"
description: "Record RTSP streams with speed control, date folders, and webhooks"
url: "https://example.com/rtsp_recorder"
init: false
startup: application
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

# Монтируем медиа и конфиг, плюс пробрасываем GPU для VA-API
map:
  - media:rw
  - config:rw
devices:
  - /dev/dri

# Параметры по умолчанию
options:
  streams: []
  default_setpts: 1
  default_expected_duration: 60
  output_dir: "/media/camera"
  event_url: null
  event_body_template: null
  use_hwaccel: false
  hw_device: "/dev/dri/renderD128"
  global_quality: 39
  ffmpeg_show_output: false

schema:
  streams:
    - url: str
      name: str?
      expected_duration: int(1,)?
      max_filesize_mb: int(0,)?
      setpts: float(0.001,)?
  default_setpts: float(0.001,)
  default_expected_duration: int(1,)
  output_dir: str
  event_url: url?
  event_body_template: str?
  use_hwaccel: bool
  hw_device: str?
  global_quality: int(0,51)?
  ffmpeg_show_output: bool
