# config.yaml — bump your version too
version: "1.0.4"

options:
  streams: []
  default_setpts: 1
  default_expected_duration: 60
  output_dir: "/media/camera"
  event_url: null
  event_body_template: null
  use_hwaccel: false
  hw_device: "/dev/dri/renderD128"
  global_quality: 39
  ffmpeg_show_output: false

schema:
  streams:
    - url: str
      name: str?
      expected_duration: int(1,)?
      max_filesize_mb: int(0,)?
      setpts: float(0.001,)?
  default_setpts: float(0.001,)
  default_expected_duration: int(1,)
  output_dir: str
  event_url: url?
  event_body_template: str?
  use_hwaccel: bool
  hw_device: str?
  global_quality: int(0,51)?
  ffmpeg_show_output: bool
